### ISSUE TITLE
Wierdish Behaviour

### ISSUE THREAD

**Issue by 0b1kn00b** [haxetink/tink_url#1]
So I'm using the path portion as a filesystem path, (it should be a subset, right?)

```
Log.hx:174: DEBUG 21/02/16 17:30:56 (Config#new@133) /media/i/projects/property
Log.hx:174: DEBUG 21/02/16 17:30:56 (TestRunner#run@56) run
Log.hx:174: DEBUG 21/02/16 17:30:56 (ListingManager#insert@351) assets/listings/f593424b-bec4-43dc-8ae9-2b3778ecca9c.json
Log.hx:174: DEBUG 21/02/16 17:30:56 (ListingManager#insert@353) /media/i/projects/assets/listings/f593424b-bec4-43dc-8ae9-2b3778ecca9c.json
```

so when I  `path.join()`, and there isn't a final slash, it removes the last node when appending. Not sure if it's a supported use case, but maybe worth mentioning.

**Comment by back2dos** [comment]
That works [as intended](https://github.com/haxetink/tink_url/blob/master/tests/TestPath.hx#L15). That is how URL paths are resolved by browsers and I think it kind of makes sense. But I see how that might be counter-intuitive for file system paths.

**Comment by 0b1kn00b** [comment]
Makes sense, that the left hand side is assumed to be leafy unless explicitly stated.
