### ISSUE TITLE
Format URL

### ISSUE THREAD

**Issue by demurgos** [haxetink/tink_url#13]
Hi,
I am having some difficulties to format an URL: create the the `UrlParts` myself and then call a function to convert them to a String (the opposite of `URL.parse`). Is there currently a way to achieve this ?

I also tried to create a new empty Url and then change the parts that I want and convert it to a string, but the parts are read-only.

All I need, is a way to easily convert between a parsed and serialized form of an URL. It seems to work fine in the direction from the serialized to parsed form but not the other way around.

**Comment by back2dos** [comment]
Hmm, never really considered that ... I'll think about a nice way to expose the functionality. In the meantime I suggest using `@:privateAccess new Url({ ... })`.

**Comment by demurgos** [comment]
Ok, thank you.
There are not that many good libraries for URL processing in Haxe so I hope that this library gets more features. For the moment I am quite happy with it but had this problem. Thank you for the tip about accessing private functions. (I did not know how to do it)

**Comment by back2dos** [comment]
FYI `thx.core` has a mutable [`Url`](https://github.com/fponticelli/thx.core/blob/master/src/thx/Url.hx) type. The thx and tink projects are quite similar in many respects. The main difference is that while thx strives for feature richness, tink aims for leanness. YAGNI and all that. So unless someone requests a feature, it is not added. It may be that thx suits your taste better. Eitherway, be sure to check it out ;)
