### ISSUE TITLE
Feature Request: QueryString Builder/Parser from/to Object

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_url#3]
Consider a data object like this:

``` js
{
    s:['1','2','3'],
    i:[1,2,3],
    d: {
        a: [2,3,4]
    },
    o: [
        {a:1, b:2},
        {c:"1", d:"2"}
    ]
}
```

It can be encoded to a query string like this:

```
s[]=1&s[]=2&s[]=3&i[]=1&i[]=2&i[]=3&d[a][]=2&d[a][]=3&d[a][]=4&o[0][a]=1&o[0][b]=2&o[1][c]=1&o[1][d]=2
```

**Comment by back2dos** [comment]
Yeah, I have plans to do something vaguely similar. The most important
thing for me was though to have an unopinionated way to just get key-value
pairs and then everyone can interpret them as they wish.

I'll close this when I'm done with my solution.

**Comment by kevinresol** [comment]
> unopinionated way to just get key-value
> pairs

Great, that's exactly what i need for ufront now:+1:

**Comment by back2dos** [comment]
Isn't this pretty much the exact same thing though? https://github.com/ufront/ufront-mvc/blob/master/src/ufront/web/url/PartialUrl.hx#L16

**Comment by kevinresol** [comment]
wow I didn't even know it existed. I should have a look. The main problem ufront now facing is that the decoding is a bit inconsistent across target

**Comment by kevinresol** [comment]
I am back with this.

What I wish now is to decode this string: 

```
s[]=1&s[]=2&s[]=3&i[]=1&i[]=2&i[]=3&d[a][]=2&d[a][]=3&d[a][]=4&o[0][a]=1&o[0][b]=2&o[1][c]=1&o[1][d]=2
```

into an object:

```
{
    s:['1','2','3'],
    i:['1','2','3'],
    d: {
        a: ['2','3','4']
    },
    o: [
        {a:'1', b:'2'},
        {c:'1', d:'2'}
    ]
}
```

I think this transformation is still un-opinionated (because the values are just plain strings), but this make it much more consumer-friendly.

**Comment by kevinresol** [comment]
Maybe I should go for tink_typecrawler.
